"""
Calculate Total Heatwave Exposures (Person-Days and Person-Events)

- Person-Days tells you the burden (how much total heat stress occurred).
- Person-Events tells you the frequency (how many times people were hit).

If Person-Days are rising faster than Person-Events, it means heatwaves are getting longer (duration per event is increasing)
"""

import pandas as pd
import xarray as xr

from my_config import DirsLocal
from python_code.shared_functions import (
    read_pop_data_processed,
    calculate_exposure_population,
)


import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import cartopy.crs as ccrs

# Set seaborn style for cleaner plots
sns.set_theme(style="whitegrid")


class AgeBands:
    INFANTS = "under_1"
    ELDERLY_65 = "over_65"
    ELDERLY_75 = "over_75"


class Metrics:
    DAYS = "heatwave_days"
    EVENTS = "heatwave_count"


def load_exposure_data(metric: str = Metrics.DAYS):
    """Load the four exposure files generated by your script."""

    if metric not in [Metrics.DAYS, Metrics.EVENTS]:
        raise ValueError(
            f"Invalid metric: {metric}. Choose 'heatwave_days' or 'heatwave_count'."
        )

    if metric == Metrics.DAYS:
        path_days_eld = DirsLocal.dir_file_elderly_exposure_abs
        path_days_inf = DirsLocal.dir_file_infants_exposure_abs

        ds_days_eld = xr.open_dataset(path_days_eld)["heatwave_days"]
        ds_days_inf = xr.open_dataset(path_days_inf)["heatwave_days"]

        return {
            AgeBands.ELDERLY_65: ds_days_eld,
            AgeBands.INFANTS: ds_days_inf,
        }
    else:
        path_events_eld = (
            DirsLocal.dir_file_elderly_exposure_abs.parent
            / "exposure_events_elderly_65.nc"
        )
        path_events_inf = (
            DirsLocal.dir_file_infants_exposure_abs.parent
            / "exposure_events_infants_0.nc"
        )

        ds_events_eld = xr.open_dataset(path_events_eld)["heatwave_count"]
        ds_events_inf = xr.open_dataset(path_events_inf)["heatwave_count"]

        return {
            AgeBands.ELDERLY_65: ds_events_eld,
            AgeBands.INFANTS: ds_events_inf,
        }


def plot_global_trends(days, events, population=AgeBands.ELDERLY_65):
    """
    Dual-axis plot: Person-Days vs Person-Events.
    Answer: Is the burden (Days) rising faster than the frequency (Events)?
    """
    days = days[population].sum(dim=["latitude", "longitude"])
    events = events[population].sum(dim=["latitude", "longitude"])

    years = days.year.values

    fig, ax1 = plt.subplots(figsize=(7, 4))

    # Plot Person-Days (Left Axis)
    color = "tab:red"
    ax1.set_xlabel("Year")
    ax1.set_ylabel("Total Person-Days (Billions)", color=color)
    # Divide by 1e9 for Billions
    ax1.plot(
        years, days / 1e9, color=color, marker="o", linewidth=2, label="Person-Days"
    )
    ax1.tick_params(axis="y", labelcolor=color)

    # Plot Person-Events (Right Axis)
    ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis
    color = "tab:blue"
    ax2.set_ylabel("Total Person-Events (Billions)", color=color)
    # Divide by 1e9 for Billions
    ax2.plot(
        years,
        events / 1e9,
        color=color,
        marker="s",
        linestyle="--",
        label="Person-Events",
    )
    ax2.tick_params(axis="y", labelcolor=color)
    ax2.grid(False)

    plt.title(f"Global Heatwave Exposure: {population}\n(Burden vs. Frequency)")
    fig.tight_layout()
    plt.savefig(
        DirsLocal.dir_figures / f"heatwave_exposure_global_trends_{population}.pdf"
    )
    plt.show()


def plot_global_trends_combined(days_ds, events_ds):
    """
    Dual-axis plot: Person-Days vs Person-Events.
    Answer: Is the burden (Days) rising faster than the frequency (Events)?
    """

    fig, ax1 = plt.subplots(figsize=(7, 4))

    # todo I need to fix the colors labels and show legends

    for population in [AgeBands.ELDERLY_65, AgeBands.INFANTS]:
        days = days_ds[population].sum(dim=["latitude", "longitude"])
        events = events_ds[population].sum(dim=["latitude", "longitude"])

        years = days.year.values

        # Plot Person-Days (Left Axis)
        color = "tab:red"
        ax1.set_xlabel("Year")
        ax1.set_ylabel("Total Person-Days (Billions)", color=color)
        # Divide by 1e9 for Billions
        ax1.plot(
            years,
            days / 1e9,
            color=color,
            marker="o",
            linewidth=2,
            label=f"Person-Days ({population})",
        )
        ax1.tick_params(axis="y", labelcolor=color)
        ax1.set(ylim=(0, 20))

        # Plot Person-Events (Right Axis)
        ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis
        color = "tab:blue"
        ax2.set_ylabel("Total Person-Events (Billions)", color=color)
        # Divide by 1e9 for Billions
        ax2.plot(
            years,
            events / 1e9,
            color=color,
            marker="s",
            linestyle="--",
            label=f"Person-Events ({population})",
        )
        ax2.tick_params(axis="y", labelcolor=color)
        ax2.set(ylim=(0, 3))
        ax2.grid(False)

    plt.title("Global Heatwave Exposure: Burden vs. Frequency (Elderly & Infants)")
    fig.tight_layout()
    plt.savefig(DirsLocal.dir_figures / "heatwave_exposure_global_trends_combined.pdf")
    plt.show()


def plot_severity_ratio(days, events, population=AgeBands.ELDERLY_65):
    """
    Calculates Days / Events to get 'Average Duration per Exposure Event'.
    """
    days = days[population].sum(dim=["latitude", "longitude"])
    events = events[population].sum(dim=["latitude", "longitude"])

    # Avoid division by zero
    ratio = days / events

    plt.figure(figsize=(7, 4))
    sns.lineplot(x=days.year, y=ratio, marker="o", color="purple")

    # Add trend line
    z = np.polyfit(days.year, ratio, 1)
    p = np.poly1d(z)
    plt.plot(days.year, p(days.year), "k--", alpha=0.5, label="Trend")

    plt.ylabel("Avg Days per Person-Event")
    plt.title(
        f"Heatwave Severity Intensity: {population}\n(Is Heatwave Duration Increasing?)"
    )
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig(DirsLocal.dir_figures / f"heatwave_severity_ratio_{population}.pdf")
    plt.show()


def plot_severity_ratio_combined(days_ds, events_ds):
    _, _ = plt.subplots(figsize=(7, 4))

    for population in [AgeBands.ELDERLY_65, AgeBands.INFANTS]:
        days = days_ds[population].sum(dim=["latitude", "longitude"])
        events = events_ds[population].sum(dim=["latitude", "longitude"])

        # Avoid division by zero
        ratio = days / events

        ax1 = sns.lineplot(x=days.year, y=ratio, marker="o", label=population)

        # get the color used by seaborn
        line = ax1.lines[-1]
        line_color = line.get_color()

        # Add trend line
        z = np.polyfit(days.year, ratio, 1)
        p = np.poly1d(z)
        ax1.plot(
            days.year,
            p(days.year),
            color=line_color,
            ls="--",
            alpha=0.5,
            label="Trend (" + population + ")",
        )

        ax1.set(ylabel="Avg Days per Person-Event", xlabel="Year")
    plt.title(
        f"Heatwave Severity Intensity: {population}\n(Is Heatwave Duration Increasing?)"
    )
    plt.legend(frameon=False)
    plt.tight_layout()
    sns.despine()
    plt.grid(True, alpha=0.3)
    plt.savefig(DirsLocal.dir_figures / "heatwave_severity_ratio_combined.pdf")
    plt.show()


def plot_exposure_map(data_dict, year=2020, population="Elderly"):
    """
    Maps the Person-Days exposure for a specific year.
    """
    data = data_dict[f"days_{population[:3].lower()}"].sel(year=year)

    # Log scale is often useful for exposure because cities dominate the map
    # We add 1 to avoid log(0) errors
    data_log = np.log10(data + 1)

    fig, ax = plt.subplots(figsize=(7, 4), subplot_kw={"projection": ccrs.Robinson()})

    p = data_log.plot(
        ax=ax,
        transform=ccrs.PlateCarree(),
        cmap="inferno",
        cbar_kwargs={"label": "Log10(Person-Days)"},
    )

    ax.coastlines()
    ax.set_title(f"Global Heatwave Exposure Map: {population} ({year})")
    plt.show()


def plot():
    print("Loading data...")
    data_days = load_exposure_data(metric=Metrics.DAYS)
    data_events = load_exposure_data(metric=Metrics.EVENTS)

    # Combined Plot for both populations
    plot_global_trends_combined(data_days, data_events)

    # 1. Global Trends
    plot_global_trends(data_days, data_events, population=AgeBands.ELDERLY_65)
    plot_global_trends(data_events, data_events, population=AgeBands.INFANTS)

    # 2. Severity Ratio - This is the "Is it getting longer?" plot
    plot_severity_ratio_combined(data_days, data_events)
    plot_severity_ratio(data_days, data_events, population=AgeBands.ELDERLY_65)
    plot_severity_ratio(data_days, data_events, population=AgeBands.INFANTS)

    # # 4. Map of latest year
    # latest_year = int(data["days_eld"].year.max())
    # plot_exposure_map(data, year=latest_year, population="Elderly")


def main():
    # 1. Load Population Data (using the improved function)
    print("Reading Population Data...")
    pop_inf, pop_eld, _, pop_75 = read_pop_data_processed(get_pop_75=True)

    # 2. Load Heatwave Metrics
    print("Reading Heatwave Metrics...")
    heatwave_metrics_files = sorted(DirsLocal.dir_results_heatwaves.glob("*.nc"))
    heatwave_metrics = xr.open_mfdataset(
        heatwave_metrics_files, combine="by_coords", parallel=True
    )

    # --- METRIC A: PERSON-DAYS (Standard) ---
    print("\n--- Calculating Person-Days (Duration Exposure) ---")

    # Infants
    exp_days_inf = calculate_exposure_population(
        data=pop_inf, heatwave_metrics=heatwave_metrics, metric="heatwave_days"
    )
    # Elderly (>65)
    exp_days_eld = calculate_exposure_population(
        pop_eld, heatwave_metrics, metric="heatwave_days"
    )
    # Very Elderly (>75)
    exp_days_75 = calculate_exposure_population(
        pop_75, heatwave_metrics, metric="heatwave_days"
    )

    # Save Person-Days
    print(f"Saving Person-Days to {DirsLocal.dir_file_elderly_exposure_abs}...")
    exp_days_eld.to_netcdf(DirsLocal.dir_file_elderly_exposure_abs)

    print(f"Saving Person-Days to {DirsLocal.dir_file_infants_exposure_abs}...")
    exp_days_inf.to_netcdf(DirsLocal.dir_file_infants_exposure_abs)

    print(f"Saving Person-Days to {DirsLocal.dir_file_above_75_exposure_abs}...")
    exp_days_75.to_netcdf(DirsLocal.dir_file_above_75_exposure_abs)

    exposures = xr.concat(
        [exp_days_inf, exp_days_eld, exp_days_75],
        dim=pd.Index([0, 65, 75], name="age_band_lower_bound"),
    )

    # This is the new file replacing the old one
    print(f"Saving {DirsLocal.dir_file_all_exposure_abs}...")
    exposures.to_netcdf(DirsLocal.dir_file_all_exposure_abs)

    # --- METRIC B: PERSON-EVENTS (New Count Exposure) ---
    print("\n--- Calculating Person-Events (Frequency Exposure) ---")

    # We create new filenames for these (add _count suffix or similar)
    file_events_eld = (
        DirsLocal.dir_file_elderly_exposure_abs.parent / "exposure_events_elderly_65.nc"
    )
    file_events_inf = (
        DirsLocal.dir_file_infants_exposure_abs.parent / "exposure_events_infants_0.nc"
    )

    # Infants
    exp_count_inf = calculate_exposure_population(
        pop_inf, heatwave_metrics, metric="heatwave_count"
    )
    # Elderly (>65)
    exp_count_eld = calculate_exposure_population(
        pop_eld, heatwave_metrics, metric="heatwave_count"
    )

    print(f"Saving Person-Events to {file_events_eld}...")
    exp_count_eld.to_netcdf(file_events_eld)

    print(f"Saving Person-Events to {file_events_inf}...")
    exp_count_inf.to_netcdf(file_events_inf)

    print("\n✅ All exposures calculated.")


if __name__ == "__main__":
    pass
    main()
    plot()
